version: '3.8'

services:
  crdb:
    image: cockroachdb/cockroach:v22.1.0
    ports:
      - "26257:26257"
      #- "8090:8080"
    command: start-single-node --insecure
    restart: unless-stopped
    volumes:
      - "crdb_volume:/cockroach/cockroach-data"

volumes:
  crdb_volume:

